---
- name: install perl and cpanm
  apt:
    pkg: $item
    state: installed
    update-cache: yes
  with_items:
    - perl
    - curl
    - cpanminus
    - gettext

- name: install sqitch dependencies
  cpanm:
    name: $item
    notest: True
  with_items:
    - Dist::Zilla
    - Dist::Zilla::Plugin::CheckExtraTests
    - Dist::Zilla::Plugin::LocaleTextDomain
    - Dist::Zilla::Plugin::VersionFromModule
    - DBD::Pg

- file:
    path: /usr/local/perl
    owner: root
    group: root
    mode: 655
    recurse: yes
    state: directory

- shell: "which sqitch"
  register: which_sqitch

- get_url:
    url: $sqitch_download_url
    dest: "/usr/local/perl/sqitch.zip"
  register: download_sqitch
  when: which_sqitch.stdout == ''

- stat:
    path: "/usr/local/perl/sqitch-{{ sqitch_version }}"
  register: sqitch_extract_dir
  when: which_sqitch.stdout == ''

- shell: "unzip /usr/local/perl/sqitch.zip -d /usr/local/perl"
  when: sqitch_extract_dir.stat.isdir is undefined or sqitch_extract_dir.stat.isdir == false
  register: sqitch_unzip
  when: which_sqitch.stdout == ''

- shell: "cd /usr/local/perl/sqitch-* && dzil install"
  when: which_sqitch.stdout == '' and sqitch_unzip is defined and sqitch_unzip.changed