---
- name: install perl and cpanm
  apt:
    pkg: "{{item}}"
    state: installed
    update-cache: yes
  with_items:
    - perl
    - curl
    - cpanminus
    - gettext

- name: install sqitch dependencies
  cpanm:
    name: "{{item}}"
    notest: True
  with_items:
    - Dist::Zilla
    - Dist::Zilla::Plugin::CheckExtraTests
    - Dist::Zilla::Plugin::LocaleTextDomain
    - Dist::Zilla::Plugin::VersionFromModule
    - DBD::Pg

- file:
    path: /usr/local/perl
    owner: root
    group: root
    mode: 655
    recurse: yes
    state: directory

- action: sqitch_facts

- get_url:
    url: "{{sqitch_download_url}}"
    dest: "/usr/local/perl/sqitch.zip"
  when: "not sqitch.installed or sqitch.version != '{{ sqitch_version }}'"

- stat:
    path: "/usr/local/perl/sqitch-{{ sqitch_version }}"
  when: "not sqitch.installed or sqitch.version != '{{ sqitch_version }}'"

- shell: "unzip /usr/local/perl/sqitch.zip -d /usr/local/perl"
  when: "not sqitch.installed or sqitch.version != '{{ sqitch_version }}'"

- shell: "cd /usr/local/perl/sqitch-* && dzil install"
  when: "not sqitch.installed or sqitch.version != '{{ sqitch_version }}'"